trigger:
  branches:
    include:
    - master
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: alastairs

jobs:
- template: templates/build.and.release.yml@recommended_practices
  parameters:
    vmImage: 'windows-latest'
    solution_to_build: Solutions/Corvus.Testing.sln
    postCustomEnvironmentVariables:
      - task: Npm@1
        displayName: 'Install Latest Azure Functions V3 Runtime'
        inputs:
          command: custom
          verbose: false
          customCommand: 'install -g azure-functions-core-tools@3 --unsafe-perm true'
    netSdkVersion: '3.x'

- job: publish
  displayName: "Publish to internal NuGet"
  dependsOn: Build
  condition: succeeded('Build')
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'e7dd1e5b-a73f-4cc9-8003-6c5c97b3f40b'
